/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pixelshop;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author redmibook
 */
public class admin extends javax.swing.JFrame {
 

    /**
     * Creates new form DashKepala
     */
    public admin() {
       setTitle("Fixed Size Window");

        // Set fixed window size
        setSize(1440, 720); // Width = 800px, Height = 600px

        // Center the window on the screen
        setLocationRelativeTo(null);

        // Disable resizing
        setResizable(false);

        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        initComponents();
        
        try {
            // Load custom font
            Font Text = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(28f);
            Font DialogText = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(30f);
            Font Heading = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(50f);
            Kategori.setFont(Text);
            Exit.setFont(Text);
            User.setFont(Text);
            Produk.setFont(Text);
            Dialog.setFont(DialogText);
            Action1.setFont(Text);
        Action2.setFont(Text);
        Cancel.setFont(Text);
        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
        }
        // Initially hide jLabel4 and jLabel10
        
     
        Action1.setVisible(false);
        Action2.setVisible(false);
        Cancel.setVisible(false);
        Exit.setVisible(false);
        User.setVisible(false);
        Produk.setVisible(false);
        Kategori.setVisible(false);

// Only run once on first click anywhere in the panel
jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
    private boolean done = false;

    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (done) return;
        done = true;

        // Hide buttons and idle image
Dialog.setVisible(false);
DialogBox.setVisible(false);
Exit.setVisible(true);
User.setVisible(true);
Produk.setVisible(true);
Kategori.setVisible(true);
    }
});


//         this.setExtendedState(JFrame.MAXIMIZED_BOTH);
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        Action1 = new javax.swing.JButton();
        Action2 = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        User = new javax.swing.JButton();
        Kategori = new javax.swing.JButton();
        Produk = new javax.swing.JButton();
        Dialog = new javax.swing.JLabel();
        DialogBox = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 720));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(255, 255, 255,0));
        jButton3.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/Setting_Main_Icon.png"))); // NOI18N
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 101, 161), 2, true));
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 70, 60));

        Action1.setBackground(new java.awt.Color(255, 255, 255,0));
        Action1.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Action1.setForeground(new java.awt.Color(255, 255, 255));
        Action1.setText("* About this shop");
        Action1.setBorder(null);
        Action1.setBorderPainted(false);
        Action1.setFocusPainted(false);
        Action1.setFocusable(false);
        Action1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Action1.setOpaque(false);
        Action1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Action1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Action1MouseExited(evt);
            }
        });
        Action1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Action1ActionPerformed(evt);
            }
        });
        jPanel1.add(Action1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 240, 30));

        Action2.setBackground(new java.awt.Color(255, 255, 255,0));
        Action2.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Action2.setForeground(new java.awt.Color(255, 255, 255));
        Action2.setText("* Who are you?");
        Action2.setBorder(null);
        Action2.setBorderPainted(false);
        Action2.setFocusPainted(false);
        Action2.setFocusable(false);
        Action2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Action2.setOpaque(false);
        Action2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Action2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Action2MouseExited(evt);
            }
        });
        Action2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Action2ActionPerformed(evt);
            }
        });
        jPanel1.add(Action2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 240, 30));

        Cancel.setBackground(new java.awt.Color(255, 255, 255,0));
        Cancel.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Cancel.setForeground(new java.awt.Color(255, 255, 255));
        Cancel.setText("* ...");
        Cancel.setBorder(null);
        Cancel.setBorderPainted(false);
        Cancel.setFocusPainted(false);
        Cancel.setFocusable(false);
        Cancel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cancel.setOpaque(false);
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelMouseExited(evt);
            }
        });
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 240, 30));

        Exit.setBackground(new java.awt.Color(255, 255, 255,0));
        Exit.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("Exit");
        Exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Exit.setBorderPainted(false);
        Exit.setFocusPainted(false);
        Exit.setFocusable(false);
        Exit.setOpaque(false);
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 370, 230, 20));

        User.setBackground(new java.awt.Color(255, 255, 255,0));
        User.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setText("Users");
        User.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        User.setBorderPainted(false);
        User.setFocusPainted(false);
        User.setFocusable(false);
        User.setOpaque(false);
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserMouseExited(evt);
            }
        });
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        jPanel1.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 230, 20));

        Kategori.setBackground(new java.awt.Color(255, 255, 255,0));
        Kategori.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Kategori.setForeground(new java.awt.Color(255, 255, 255));
        Kategori.setText("Kategori");
        Kategori.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Kategori.setBorderPainted(false);
        Kategori.setFocusPainted(false);
        Kategori.setFocusable(false);
        Kategori.setOpaque(false);
        Kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KategoriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KategoriMouseExited(evt);
            }
        });
        Kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategoriActionPerformed(evt);
            }
        });
        jPanel1.add(Kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 230, 30));

        Produk.setBackground(new java.awt.Color(255, 255, 255,0));
        Produk.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Produk.setForeground(new java.awt.Color(255, 255, 255));
        Produk.setText("Produk");
        Produk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Produk.setBorderPainted(false);
        Produk.setFocusPainted(false);
        Produk.setFocusable(false);
        Produk.setOpaque(false);
        Produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProdukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProdukMouseExited(evt);
            }
        });
        Produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdukActionPerformed(evt);
            }
        });
        jPanel1.add(Produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 230, 20));

        Dialog.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        Dialog.setForeground(new java.awt.Color(255, 255, 255));
        Dialog.setText("*The control of this world in your hands fills you with emptiness.");
        Dialog.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(Dialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 970, 80));

        DialogBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/dialouge box.png"))); // NOI18N
        DialogBox.setText("jLabel3");
        jPanel1.add(DialogBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 380));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/ezgif-30a76e94aefd66.gif"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 1440, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        Cancel.setVisible(false);
        Action1.setVisible(false);
        Action2.setVisible(false);
    }//GEN-LAST:event_CancelActionPerformed

    private void CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseExited
        // TODO add your handling code here:
        Cancel.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_CancelMouseExited

    private void CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseEntered
        // TODO add your handling code here:
        Cancel.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_CancelMouseEntered

    private void Action2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Action2ActionPerformed
        // TODO add your handling code here:
        Cancel.setVisible(false);
        Action1.setVisible(false);
        Action2.setVisible(false);

        Dialog.setVisible(true);
        Dialog.setText("I am the creator of this 'world'.");

        final int[] clickCount = {0}; // Use array to allow modification inside inner class

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickCount[0]++;

                if (clickCount[0] == 1) {
                    Dialog.setText("Nah, just kidding. I'm Ryuku, the owner of this shop.");
                } else if (clickCount[0] == 2) {
                    Dialog.setText("*The control of this world in your hands fills you with emptiness.");
                } else if (clickCount[0] == 3) {
                    Dialog.setVisible(false);
                } else {
                    removeMouseListener(this);
                }
            }
        });
    }//GEN-LAST:event_Action2ActionPerformed

    private void Action2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Action2MouseExited
        // TODO add your handling code here:
        Action2.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Action2MouseExited

    private void Action2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Action2MouseEntered
        // TODO add your handling code here:
        Action2.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_Action2MouseEntered

    private void Action1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Action1ActionPerformed
        // TODO add your handling code here:
        Cancel.setVisible(false);
        Action1.setVisible(false);
        Action2.setVisible(false);

        Dialog.setVisible(true);
        Dialog.setText("It just opened this morning, feel honored to be the first customer.");

        final int[] clickCount = {0}; // Use array to allow modification inside inner class

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickCount[0]++;

                if (clickCount[0] == 1) {
                    Dialog.setText("I will give you an achievement once I master Java Netbeans, stay tuned.");
                } else if (clickCount[0] == 2) {
                    Dialog.setText("What are you searching for?");
                } else if (clickCount[0] == 3) {
                    Dialog.setVisible(false);
   
                } else {
                    removeMouseListener(this);
                }
            }
        });
    }//GEN-LAST:event_Action1ActionPerformed

    private void Action1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Action1MouseExited
        // TODO add your handling code here:
        Action1.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Action1MouseExited

    private void Action1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Action1MouseEntered
        // TODO add your handling code here:
        Action1.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_Action1MouseEntered

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        // TODO add your handling code here:
        Exit.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_ExitMouseExited

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        Exit.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_ExitMouseEntered

    private void UserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseEntered
        // TODO add your handling code here:
        User.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_UserMouseEntered

    private void UserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseExited
        // TODO add your handling code here:
        User.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_UserMouseExited

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        // TODO add your handling code here:
        new UserView().show();
        this.dispose();
    }//GEN-LAST:event_UserActionPerformed

    private void ProdukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdukMouseEntered
        // TODO add your handling code here:
        Produk.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_ProdukMouseEntered

    private void ProdukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdukMouseExited
        // TODO add your handling code here:
        Produk.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_ProdukMouseExited

    private void ProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdukActionPerformed
        // TODO add your handling code here:
        new ProductView().show();
        this.dispose();
    }//GEN-LAST:event_ProdukActionPerformed

    private void KategoriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KategoriMouseEntered
        // TODO add your handling code here:
        Kategori.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_KategoriMouseEntered

    private void KategoriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KategoriMouseExited
        // TODO add your handling code here:
         Kategori.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_KategoriMouseExited

    private void KategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategoriActionPerformed
        // TODO add your handling code here:
         new KategoriView().show();
        this.dispose();
    }//GEN-LAST:event_KategoriActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Setting().show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Action1;
    private javax.swing.JButton Action2;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel Dialog;
    private javax.swing.JLabel DialogBox;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Kategori;
    private javax.swing.JButton Produk;
    private javax.swing.JButton User;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
