/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pixelshop;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author redmibook
 */
public class Garden extends javax.swing.JFrame {

    /**
     * Creates new form DashKepala
     */
    private void doFinalAction() {
        // The actual final thing to do
        Action1.setVisible(false);
        Action2.setVisible(false);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            private boolean done = false;

            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (done) {
                    return;
                }
                done = true;
                Dialog.setVisible(false);
                DialogBox.setVisible(false);
                SecretBoss.setVisible(true);
            }
        });
    }

    public Garden() {
        setTitle("Fixed Size Window");

        // Set fixed window size
        setSize(1440, 720); // Width = 800px, Height = 600px

        // Center the window on the screen
        setLocationRelativeTo(null);

        // Disable resizing
        setResizable(false);

        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        initComponents();

        try {
            // Load custom font
            Font Text = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(28f);
            Font DialogText = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(30f);
            Font Heading = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(50f);
            SecretBoss.setFont(Text);
            Dialog.setFont(DialogText);
            Action1.setFont(Text);
            Action2.setFont(Text);
        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
        }
        // Initially hide jLabel4 and jLabel10

        Action1.setVisible(false);
        Action2.setVisible(false);
        SecretBoss.setVisible(false);

// Only run once on first click anywhere in the panel
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            private boolean done = false;

            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (done) {
                    return;
                }
                done = true;
                Action1.setVisible(true);
                Action2.setVisible(true);
            }
        });

//         this.setExtendedState(JFrame.MAXIMIZED_BOTH);
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Action2 = new javax.swing.JButton();
        Action1 = new javax.swing.JButton();
        Dialog = new javax.swing.JLabel();
        DialogBox = new javax.swing.JLabel();
        SecretBoss = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 720));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Action2.setBackground(new java.awt.Color(255, 255, 255,0));
        Action2.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Action2.setForeground(new java.awt.Color(255, 255, 255));
        Action2.setText("* RESIST");
        Action2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Action2.setBorderPainted(false);
        Action2.setFocusPainted(false);
        Action2.setFocusable(false);
        Action2.setOpaque(false);
        Action2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Action2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Action2MouseExited(evt);
            }
        });
        Action2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Action2ActionPerformed(evt);
            }
        });
        jPanel1.add(Action2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 150, 20));

        Action1.setBackground(new java.awt.Color(255, 255, 255,0));
        Action1.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Action1.setForeground(new java.awt.Color(255, 255, 255));
        Action1.setText("* GO BACK");
        Action1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Action1.setBorderPainted(false);
        Action1.setFocusPainted(false);
        Action1.setFocusable(false);
        Action1.setOpaque(false);
        Action1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Action1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Action1MouseExited(evt);
            }
        });
        Action1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Action1ActionPerformed(evt);
            }
        });
        jPanel1.add(Action1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 150, 20));

        Dialog.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        Dialog.setForeground(new java.awt.Color(255, 255, 255));
        Dialog.setText("* You were somewhere you shouldn'tve been. go BACK?");
        Dialog.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(Dialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 970, 100));

        DialogBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/dialouge box.png"))); // NOI18N
        jPanel1.add(DialogBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 380));

        SecretBoss.setBackground(new java.awt.Color(255, 255, 255,0));
        SecretBoss.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        SecretBoss.setForeground(new java.awt.Color(255, 255, 255));
        SecretBoss.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SecretBoss.setBorderPainted(false);
        SecretBoss.setFocusPainted(false);
        SecretBoss.setFocusable(false);
        SecretBoss.setOpaque(false);
        SecretBoss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SecretBossMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SecretBossMouseExited(evt);
            }
        });
        SecretBoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecretBossActionPerformed(evt);
            }
        });
        jPanel1.add(SecretBoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 130, 280));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/Route2.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 1440, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SecretBossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecretBossActionPerformed
         // Tutup halaman sekarang
    this.dispose();

    // Buka halaman baru yang berisi MiniRPG
    JFrame frame = new JFrame("Mini Undertale RPG");
    MiniRPG game = new MiniRPG();
    frame.add(game);
    frame.pack();
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);
    game.requestFocusInWindow(); // penting biar keyboard langsung fokus

    }//GEN-LAST:event_SecretBossActionPerformed

    private void SecretBossMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SecretBossMouseExited
        // TODO add your handling code here:
        SecretBoss.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_SecretBossMouseExited

    private void SecretBossMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SecretBossMouseEntered
        // TODO add your handling code here:
        SecretBoss.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_SecretBossMouseEntered

    private void Action1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Action1MouseEntered
        // TODO add your handling code here:
        Action1.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_Action1MouseEntered

    private void Action1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Action1MouseExited
        // TODO add your handling code here:
        Action1.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Action1MouseExited

    private void Action1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Action1ActionPerformed
        // TODO add your handling code here:
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_Action1ActionPerformed

    private void Action2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Action2MouseEntered
        // TODO add your handling code here:
        Action2.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_Action2MouseEntered

    private void Action2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Action2MouseExited
        // TODO add your handling code here:
        Action2.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Action2MouseExited

    private void Action2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Action2ActionPerformed
        // Step 1: First warning
        Dialog.setText("You better go BACK.");
        Action1.setVisible(false);
        Action2.setVisible(false);

        // Step 2: After 1 second, show Action1 + Action2 with multi-click behavior
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            Action1.setText("* BACK");
            Action1.setVisible(true);
            Action2.setVisible(true);

            final int[] clickCount = {0};

            // Hapus listener lama supaya gak numpuk
            for (java.awt.event.ActionListener al : Action2.getActionListeners()) {
                Action2.removeActionListener(al);
            }

            // Listener multi-click dengan delay muncul tombol
            Action2.addActionListener(ev -> {
                clickCount[0]++;

                // Sembunyikan tombol dulu
                Action2.setVisible(false);
                Action1.setVisible(false);

                switch (clickCount[0]) {
                    case 1:
                        Dialog.setText("Maybe you don't understand english?");
                        break;
                    case 2:
                        Dialog.setText("Tekan tombol 'BACK' plis.");
                        break;
                    case 3:
                        Dialog.setText("..BACK = good, Resist = bad.");
                        break;
                    case 4:
                        Dialog.setText("THAT'S NOT CLEAR ENOUGH???");
                        break;
                    case 5:
                        Dialog.setText("BRO? ekhem. There's no turning back after this.");
                        break;
                    case 6:
                        Dialog.setText("Why I made this route if not to be explored, you said? Not wrong...");
                        break;
                    case 7:
                        Dialog.setText("...Last chance. Read CAREFULLY");
                        break;
                    case 8:
                        Dialog.setText("OK, Then you may resist >:(");
                        Action2.setText("* SNAP");
                        Action1.setText("* RESIST");
                        break;
                    case 9:
                        Dialog.setText("(* Suddenly you couldn't hear it's annoying voice anymore.)");
                        doFinalAction();
                        return; // Stop di sini, jangan munculkan tombol lagi
                }

                // Timer buat munculin tombol lagi setelah 1 detik
                javax.swing.Timer showButtonTimer = new javax.swing.Timer(1000, ev2 -> {
                    Action2.setVisible(true);
                    Action1.setVisible(true);
                });
                showButtonTimer.setRepeats(false);
                showButtonTimer.start();

            });
        });

        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_Action2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Garden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Garden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Garden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Garden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Garden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Action1;
    private javax.swing.JButton Action2;
    private javax.swing.JLabel Dialog;
    private javax.swing.JLabel DialogBox;
    private javax.swing.JButton SecretBoss;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
