/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pixelshop;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author redmibook
 * 
 */
class ComboItem {
    private String label;
    private int value;

    public ComboItem(String label, int value) {
        this.label = label;
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    @Override
    public String toString() {
        return label;
    }
}


public class Introduce extends javax.swing.JFrame {
    private DefaultTableModel model=null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k=new koneksi();

    /**
     * Creates new form 
     * 
     */
    
    public Introduce() {
        setTitle("Fixed Size Window");

        // Set fixed window size
        setSize(1440, 720); // Width = 800px, Height = 600px

        // Center the window on the screen
        setLocationRelativeTo(null);

        // Disable resizing
        setResizable(false);

        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        initComponents();
        // Add this after initComponents(); in your Introduce constructor
jComboBox1.removeAllItems();
jComboBox1.addItem(new ComboItem("Supplier", 2));
jComboBox1.addItem(new ComboItem("Customer", 3));



        try {
            // Load custom font
            Font Text = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(24f);
            Font Dialog = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(30f);
            Font Label = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(20f);
            jLabel3.setFont(Label);
            jLabel4.setFont(Label);
            jLabel5.setFont(Label);
            btn_logout.setFont(Dialog);
            tombolsimpanbarang.setFont(Dialog);
            jLabel1.setFont(Label);
            jLabel6.setFont(Label);
            jLabel7.setFont(Label);
            jLabel8.setFont(Label);
            jLabel9.setFont(Label);
            jLabel10.setFont(Dialog);
            textJudul.setFont(Text);
            textDeskripsi.setFont(Text);
            textPenerbit.setFont(Text);
            textPengarang.setFont(Text);
            textStok.setFont(Text);
            jComboBox1.setFont(Text);
            
            
            
        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
        }
        k.connect();
        
      
    }
    
    class TambahBarang {
    Integer level;
    String nama, username, password, notelp, alamat;

    public TambahBarang(String nama, String username, String password, String notelp, String alamat, Integer level) {
        this.nama = nama;
        this.username = username;
        this.password = password;
        this.notelp = notelp;
        this.alamat = alamat;
        this.level = level;
    }
}

    
        
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        tombolsimpanbarang = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textJudul = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textPengarang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        textPenerbit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textDeskripsi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textStok = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("* Please introduce yourself.");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 650, 80));

        tombolsimpanbarang.setBackground(new java.awt.Color(255, 255, 255,0));
        tombolsimpanbarang.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        tombolsimpanbarang.setForeground(new java.awt.Color(255, 255, 255));
        tombolsimpanbarang.setText("* My name is...");
        tombolsimpanbarang.setBorderPainted(false);
        tombolsimpanbarang.setFocusPainted(false);
        tombolsimpanbarang.setFocusable(false);
        tombolsimpanbarang.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        tombolsimpanbarang.setOpaque(false);
        tombolsimpanbarang.setRequestFocusEnabled(false);
        tombolsimpanbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolsimpanbarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolsimpanbarangMouseExited(evt);
            }
        });
        tombolsimpanbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolsimpanbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tombolsimpanbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 600, 210, 40));

        btn_logout.setBackground(new java.awt.Color(255, 255, 255,0));
        btn_logout.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("* Nevermind.");
        btn_logout.setBorderPainted(false);
        btn_logout.setFocusPainted(false);
        btn_logout.setFocusable(false);
        btn_logout.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_logout.setOpaque(false);
        btn_logout.setRequestFocusEnabled(false);
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 210, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/dialouge box.png"))); // NOI18N
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 1100, 320));

        jLabel3.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 200, -1));

        textJudul.setBackground(new java.awt.Color(0, 0, 0));
        textJudul.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        textJudul.setForeground(new java.awt.Color(255, 255, 255));
        textJudul.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));
        textJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJudulActionPerformed(evt);
            }
        });
        getContentPane().add(textJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 390, 60));

        jLabel4.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 210, -1));

        textPengarang.setBackground(new java.awt.Color(0, 0, 0));
        textPengarang.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        textPengarang.setForeground(new java.awt.Color(255, 255, 255));
        textPengarang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));
        getContentPane().add(textPengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 390, 60));

        jLabel1.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 230, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));
        jComboBox1.setFocusable(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 390, 60));

        textPenerbit.setBackground(new java.awt.Color(0, 0, 0));
        textPenerbit.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        textPenerbit.setForeground(new java.awt.Color(255, 255, 255));
        textPenerbit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));
        textPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPenerbitActionPerformed(evt);
            }
        });
        getContentPane().add(textPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 390, 60));

        jLabel6.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Level");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 240, -1));

        jLabel7.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 250, -1));

        textDeskripsi.setBackground(new java.awt.Color(0, 0, 0));
        textDeskripsi.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        textDeskripsi.setForeground(new java.awt.Color(255, 255, 255));
        textDeskripsi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));
        getContentPane().add(textDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 390, 60));

        jLabel5.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 290, -1));

        textStok.setBackground(new java.awt.Color(0, 0, 0));
        textStok.setFont(new java.awt.Font("Rubik", 0, 18)); // NOI18N
        textStok.setForeground(new java.awt.Color(255, 255, 255));
        textStok.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));
        getContentPane().add(textStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 390, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/login_pixlshop.gif"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textJudulActionPerformed

    private void tombolsimpanbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolsimpanbarangActionPerformed
        // TODO add your handling code here:
        
        try {
        String nama = textJudul.getText();
String username = textPengarang.getText();
String password = textPenerbit.getText();
String notelp = textDeskripsi.getText();
String alamat = textStok.getText();
ComboItem selectedItem = (ComboItem) jComboBox1.getSelectedItem();
int level = ((ComboItem) jComboBox1.getSelectedItem()).getValue();


if ("Ryuku".equalsIgnoreCase(username) || "Ryuku".equalsIgnoreCase(nama)) {
    Random rand = new Random();
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

    // Function to spam chaotic popups for given milliseconds
    Runnable spamPopups = () -> {
        long endTime = System.currentTimeMillis() + 500; // 1 seconds
        while (System.currentTimeMillis() < endTime) {
            final JOptionPane optionPane = new JOptionPane(
                "YOUR REAL NAME.",
                JOptionPane.WARNING_MESSAGE
            );

            final JDialog dialog = optionPane.createDialog("YOUR REAL NAME?");
            dialog.setModal(false);

            int x = rand.nextInt(screenSize.width - 200);
            int y = rand.nextInt(screenSize.height - 100);
            dialog.setLocation(x, y);

            new javax.swing.Timer(1000, e -> dialog.dispose()).start();

            dialog.setVisible(true);

            try { Thread.sleep(5); } catch (InterruptedException ex) {}
        }
    };
    
     Runnable spamPopups2 = () -> {
        long endTime = System.currentTimeMillis() + 500; // 1 seconds
        while (System.currentTimeMillis() < endTime) {
            final JOptionPane optionPane = new JOptionPane(
                "TRY AGAIN.",
                JOptionPane.WARNING_MESSAGE
            );

            final JDialog dialog = optionPane.createDialog("???");
            dialog.setModal(false);

            int x = rand.nextInt(screenSize.width - 50);
            int y = rand.nextInt(screenSize.height - 100);
            dialog.setLocation(x, y);

            new javax.swing.Timer(1000, e -> dialog.dispose()).start();

            dialog.setVisible(true);

            try { Thread.sleep(3); } catch (InterruptedException ex) {}
        }
    };

    // Phase 1: spam popups
    spamPopups.run();

    // Phase 2: big centered dialog that waits for OK
    JOptionPane.showMessageDialog(
        null,
        "What are YOU trying to do?",
        "?????????????????????????",
        JOptionPane.WARNING_MESSAGE,
        null
    );

    // Phase 3: spam popups again, then exit
    spamPopups2.run();

    System.exit(0);
}

if (nama.isEmpty() || username.isEmpty() || password.isEmpty() ||
    notelp.isEmpty() || alamat.isEmpty() || selectedItem == null) {
    JOptionPane.showMessageDialog(null, "Sorry? I didn't catch that.");
    return; // stop lanjut ke proses simpan
}
if (!notelp.matches("\\d{12,}")) {
    JOptionPane.showMessageDialog(null, "Don't play around, what's your real number?");
    return;
}





        TambahBarang b = new TambahBarang(nama, username, password, notelp, alamat, level);

        stat = k.getKoneksi().prepareStatement("INSERT INTO `user` (nama, username, password, notelp, alamat1, level) VALUES (?, ?, ?, ?, ?, ?)");
        stat.setString(1, b.nama);
        stat.setString(2, b.username);
        stat.setString(3, b.password);
        stat.setString(4, b.notelp);
        stat.setString(5, b.alamat);
        stat.setInt(6, b.level);
        stat.executeUpdate();

        jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            btn_logout.setVisible(false);
            tombolsimpanbarang.setVisible(false);
            jLabel1.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            textJudul.setVisible(false);
            textDeskripsi.setVisible(false);
            textPenerbit.setVisible(false);
            textPengarang.setVisible(false);
            textStok.setVisible(false);
            jComboBox1.setVisible(false);
            jLabel10.setText("*Kay, nice to meet you " + textJudul.getText() + ".");
            this.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        new Login().setVisible(true);
        dispose();
    }
});
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_tombolsimpanbarangActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        new Login().show();
this.dispose();

    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        // TODO add your handling code here:
        btn_logout.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        // TODO add your handling code here:
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_logoutMouseExited

    private void tombolsimpanbarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolsimpanbarangMouseEntered
        // TODO add your handling code here:
        tombolsimpanbarang.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_tombolsimpanbarangMouseEntered

    private void tombolsimpanbarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolsimpanbarangMouseExited
        // TODO add your handling code here:
        tombolsimpanbarang.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_tombolsimpanbarangMouseExited

    private void textPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPenerbitActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Introduce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Introduce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Introduce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Introduce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Introduce().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logout;
    private javax.swing.JComboBox<ComboItem> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textDeskripsi;
    private javax.swing.JTextField textJudul;
    private javax.swing.JTextField textPenerbit;
    private javax.swing.JTextField textPengarang;
    private javax.swing.JTextField textStok;
    private javax.swing.JButton tombolsimpanbarang;
    // End of variables declaration//GEN-END:variables
}
