/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pixelshop;


import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;


/**
 *
 * @author redmibook
 */
public class order extends javax.swing.JFrame {

    /**
     * Creates new form DashKepala
     */
    public order() {
       setTitle("Fixed Size Window");

        // Set fixed window size
        setSize(1440, 720); // Width = 800px, Height = 600px

        // Center the window on the screen
        setLocationRelativeTo(null);

        // Disable resizing
        setResizable(false);

        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        initComponents();
        loadProducts();
        try {
            // Load custom font
            Font Text = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(28f);
            Font DialogText = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(18f);
            Font Heading = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(50f);
          Bubble.setFont(DialogText);
          CancelOrder.setFont(Text);
          Cancel.setFont(Text);
          Check.setFont(Text);
          NextBtn.setFont(Text);
          PrevBtn.setFont(Text);
          Title.setFont(Heading);
  
        
        jList2.setCellRenderer(new DefaultListCellRenderer() {
    public Component getListCellRendererComponent(JList<?> list, Object value, int index,
                                                  boolean isSelected, boolean cellHasFocus) {
        JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        String originalText = value.toString();
        label.setText("* " + originalText);
        if (isSelected) {
            label.setBackground(Color.BLACK);
            label.setForeground(Color.YELLOW);   
        } else {
            label.setBackground(Color.BLACK); // Custom selected bg
            label.setForeground(Color.WHITE);   
        
        }
        label.setFont(Text);
        label.setBorder(null);
        return label;
    }
});
        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
        }
        
        Idle.setVisible(false);
        SmilingSpeaking.setVisible(false);
        NormalSpeaking.setVisible(false);
    }
    
    
    
  

    
 private void loadProducts() {
    try {
        Connection conn = koneksi.getKoneksi();

        String sql = " SELECT DISTINCT n.order_time FROM nota n JOIN transaksi t ON n.id_nota = t.id_nota WHERE t.id_customer = ? ";

        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setInt(1, User.currentUserId); // filter by logged-in user

        ResultSet rs = stmt.executeQuery();

        DefaultListModel<String> productModel = new DefaultListModel<>();
        while (rs.next()) {
            productModel.addElement(rs.getString("order_time"));
        }
        jList2.setModel(productModel);

    } catch (SQLException e) {
        e.printStackTrace();
    }
    System.out.println("Current user id: " + User.currentUserId);

}


    
   





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        CancelOrder = new javax.swing.JButton();
        PrevBtn = new javax.swing.JButton();
        NextBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Bubble = new javax.swing.JTextArea();
        TextBubble = new javax.swing.JLabel();
        Check = new javax.swing.JButton();
        ProductList = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        HappySpeaking = new javax.swing.JLabel();
        SmilingSpeaking = new javax.swing.JLabel();
        NormalSpeaking = new javax.swing.JLabel();
        Idle = new javax.swing.JLabel();
        DialogBox = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 720));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Lucida Calligraphy", 1, 60)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Your Orders");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 550, 130));

        Cancel.setBackground(new java.awt.Color(255, 255, 255,0));
        Cancel.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Cancel.setForeground(new java.awt.Color(255, 255, 255));
        Cancel.setText("* BACK");
        Cancel.setBorder(null);
        Cancel.setBorderPainted(false);
        Cancel.setFocusPainted(false);
        Cancel.setFocusable(false);
        Cancel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cancel.setOpaque(false);
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelMouseExited(evt);
            }
        });
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 620, 240, 30));

        CancelOrder.setBackground(new java.awt.Color(255, 255, 255,0));
        CancelOrder.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        CancelOrder.setForeground(new java.awt.Color(255, 255, 255));
        CancelOrder.setText("* CANCEL ORDER");
        CancelOrder.setBorder(null);
        CancelOrder.setBorderPainted(false);
        CancelOrder.setFocusPainted(false);
        CancelOrder.setFocusable(false);
        CancelOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CancelOrder.setOpaque(false);
        CancelOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelOrderMouseExited(evt);
            }
        });
        CancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelOrderActionPerformed(evt);
            }
        });
        jPanel1.add(CancelOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, 250, 20));

        PrevBtn.setBackground(new java.awt.Color(255, 255, 255,0));
        PrevBtn.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        PrevBtn.setForeground(new java.awt.Color(255, 255, 255));
        PrevBtn.setText("< PREV");
        PrevBtn.setBorder(null);
        PrevBtn.setBorderPainted(false);
        PrevBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PrevBtn.setOpaque(false);
        PrevBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PrevBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PrevBtnMouseExited(evt);
            }
        });
        PrevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrevBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PrevBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 90, 20));

        NextBtn.setBackground(new java.awt.Color(255, 255, 255,0));
        NextBtn.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        NextBtn.setForeground(new java.awt.Color(255, 255, 255));
        NextBtn.setText("NEXT >");
        NextBtn.setBorder(null);
        NextBtn.setBorderPainted(false);
        NextBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NextBtn.setOpaque(false);
        NextBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NextBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NextBtnMouseExited(evt);
            }
        });
        NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtnActionPerformed(evt);
            }
        });
        jPanel1.add(NextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 90, 20));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setRequestFocusEnabled(false);
        jScrollPane1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setWheelScrollingEnabled(false);

        Bubble.setEditable(false);
        Bubble.setBackground(new Color(0, 0, 0, 0));
        Bubble.setColumns(5);
        Bubble.setLineWrap(true);
        Bubble.setRows(2);
        Bubble.setText("coming straight from your house~!");
        Bubble.setWrapStyleWord(true);
        Bubble.setAutoscrolls(false);
        Bubble.setFocusable(false);
        Bubble.setOpaque(false);
        Bubble.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(Bubble);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 260, 140, 100));

        TextBubble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/TextBubble.png"))); // NOI18N
        jPanel1.add(TextBubble, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, 250, 170));

        Check.setBackground(new java.awt.Color(255, 255, 255,0));
        Check.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Check.setForeground(new java.awt.Color(255, 255, 255));
        Check.setText("* CHECK");
        Check.setBorder(null);
        Check.setBorderPainted(false);
        Check.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Check.setOpaque(false);
        Check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CheckMouseExited(evt);
            }
        });
        Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckActionPerformed(evt);
            }
        });
        jPanel1.add(Check, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, 180, 20));

        ProductList.setBorder(null);

        jList2.setBackground(new java.awt.Color(0, 0, 0));
        jList2.setForeground(new java.awt.Color(255, 255, 255));
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        ProductList.setViewportView(jList2);

        jPanel1.add(ProductList, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 430, 420));

        HappySpeaking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/HappySpeaking-ezgif.com-effects.gif"))); // NOI18N
        jPanel1.add(HappySpeaking, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 590, 380));

        SmilingSpeaking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/smilingspeaking.gif"))); // NOI18N
        jPanel1.add(SmilingSpeaking, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 590, 380));

        NormalSpeaking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/normalspeaking.gif"))); // NOI18N
        jPanel1.add(NormalSpeaking, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 590, 380));

        Idle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/idle.gif"))); // NOI18N
        jPanel1.add(Idle, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 590, 380));

        DialogBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/dialouge box lg.png"))); // NOI18N
        DialogBox.setText("jLabel3");
        jPanel1.add(DialogBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/download.gif"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -490, 2110, 1620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseEntered
        // TODO add your handling code here:
        Cancel.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_CancelMouseEntered

    private void CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseExited
        // TODO add your handling code here:
        Cancel.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_CancelMouseExited

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        new indoor().show();
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void CancelOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelOrderMouseEntered
        // TODO add your handling code here:
        CancelOrder.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_CancelOrderMouseEntered

    private void CancelOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelOrderMouseExited
        // TODO add your handling code here:
        CancelOrder.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_CancelOrderMouseExited

    private void CancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelOrderActionPerformed
                new cart().show();
                this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelOrderActionPerformed

    private void CheckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckMouseEntered
        // TODO add your handling code here:
        Check.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_CheckMouseEntered

    private void CheckMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckMouseExited
        // TODO add your handling code here:
        Check.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_CheckMouseExited

    private void CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckActionPerformed
         try {
        Connection conn = koneksi.getKoneksi();
        String selectedProduct = jList2.getSelectedValue();

        String getIdQuery = "SELECT id_nota FROM nota WHERE order_time = ?";
        PreparedStatement getIdStmt = conn.prepareStatement(getIdQuery);
        getIdStmt.setString(1, selectedProduct);
        ResultSet rs = getIdStmt.executeQuery();

        if (rs.next()) {
            int idNota = rs.getInt("id_nota");

            // ✅ Open the detail page and pass the ID
            NotaDetail detailPage = new NotaDetail(idNota);
            detailPage.setVisible(true);
            this.dispose(); // optional: close current window

        } else {
            Bubble.setText("Hm? I don't think I recognize that product.");
        }

    } catch (Exception e) {
        e.printStackTrace();
        Bubble.setText("Error processing request: " + e.getMessage());
    }
    }//GEN-LAST:event_CheckActionPerformed

    private void NextBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextBtnMouseEntered
        // TODO add your handling code here:
        NextBtn.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_NextBtnMouseEntered

    private void NextBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextBtnMouseExited
        // TODO add your handling code here:
        NextBtn.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_NextBtnMouseExited

    private void NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NextBtnActionPerformed

    private void PrevBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrevBtnMouseEntered
        // TODO add your handling code here:
        PrevBtn.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_PrevBtnMouseEntered

    private void PrevBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrevBtnMouseExited
        // TODO add your handling code here:
        PrevBtn.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_PrevBtnMouseExited

    private void PrevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrevBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrevBtnActionPerformed

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
      // Assume 'conn' is your valid database connection
// String selectedProduct = jList2.getSelectedValue(); // Get the selected item
//    if (selectedProduct != null) {
//        try {
//            Connection conn = koneksi.getKoneksi();
//            String sql = "SELECT jumlah, harga FROM produk WHERE nama = ?";
//            PreparedStatement stmt = conn.prepareStatement(sql);
//            stmt.setString(1, selectedProduct);
//            ResultSet rs = stmt.executeQuery();
//
//            if (rs.next()) {
//                int jumlah = rs.getInt("jumlah");
//                double harga = rs.getDouble("harga");
//
//                Bubble.setText(
//                    selectedProduct + "?" +
//                    "\nI have " + jumlah + " of those." +
//                    "\nIt's only " + String.format("Rp%,.0f", harga).replace(',', '.') + 
//                    "\n you intrested?"
//                );
//                if (jList2.getSelectedIndex() == -1) {
//    Bubble.setText("found anything intresting?");
//}
//            }
//            NormalSpeaking.setVisible(true);
//            HappySpeaking.setVisible(false);
//            SmilingSpeaking.setVisible(false);
//            Idle.setVisible(false);
//
//        } catch (SQLException e) {
//            e.printStackTrace();
//        }
//    }
    }//GEN-LAST:event_jList2ValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextArea Bubble;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton CancelOrder;
    private javax.swing.JButton Check;
    private javax.swing.JLabel DialogBox;
    private javax.swing.JLabel HappySpeaking;
    private javax.swing.JLabel Idle;
    private javax.swing.JButton NextBtn;
    private javax.swing.JLabel NormalSpeaking;
    private javax.swing.JButton PrevBtn;
    private javax.swing.JScrollPane ProductList;
    private javax.swing.JLabel SmilingSpeaking;
    private javax.swing.JLabel TextBubble;
    private javax.swing.JLabel Title;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
