/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pixelshop;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author redmibook
 */
public class Route extends javax.swing.JFrame {
 

    /**
     * Creates new form DashKepala
     */
    public Route() {
       setTitle("Fixed Size Window");

        // Set fixed window size
        setSize(1440, 720); // Width = 800px, Height = 600px

        // Center the window on the screen
        setLocationRelativeTo(null);

        // Disable resizing
        setResizable(false);

        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        initComponents();
        
        try {
            // Load custom font
            Font Text = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(28f);
            Font DialogText = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(30f);
            Font Heading = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(50f);
            Exit.setFont(Text);
            Dialog.setFont(DialogText);
        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
        }
        // Initially hide jLabel4 and jLabel10
        
     
        Garden.setVisible(false);
        Exit.setVisible(false);

// Only run once on first click anywhere in the panel
jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
    private boolean done = false;

    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (done) return;
        done = true;

        // Hide buttons and idle image
Dialog.setVisible(false);
DialogBox.setVisible(false);
Exit.setVisible(true);
Garden.setVisible(true);
    }
});


//         this.setExtendedState(JFrame.MAXIMIZED_BOTH);
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        Dialog = new javax.swing.JLabel();
        DialogBox = new javax.swing.JLabel();
        Garden = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 720));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setBackground(new java.awt.Color(255, 255, 255,0));
        Exit.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Exit.setBorderPainted(false);
        Exit.setFocusPainted(false);
        Exit.setFocusable(false);
        Exit.setOpaque(false);
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 260, 70, 160));

        Dialog.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        Dialog.setForeground(new java.awt.Color(255, 255, 255));
        Dialog.setText("* ...");
        Dialog.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(Dialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 970, 80));

        DialogBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/dialouge box.png"))); // NOI18N
        jPanel1.add(DialogBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 380));

        Garden.setBackground(new java.awt.Color(255, 255, 255,0));
        Garden.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Garden.setForeground(new java.awt.Color(255, 255, 255));
        Garden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Garden.setBorderPainted(false);
        Garden.setFocusPainted(false);
        Garden.setFocusable(false);
        Garden.setOpaque(false);
        Garden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GardenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GardenMouseExited(evt);
            }
        });
        Garden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GardenActionPerformed(evt);
            }
        });
        jPanel1.add(Garden, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 190, 360));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/route.gif"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 1440, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        // TODO add your handling code here:
        Exit.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_ExitMouseExited

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        Exit.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_ExitMouseEntered

    private void GardenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GardenMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_GardenMouseEntered

    private void GardenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GardenMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_GardenMouseExited

    private void GardenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GardenActionPerformed
        new Garden().show();
        this.dispose();
    }//GEN-LAST:event_GardenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Route.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Route().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dialog;
    private javax.swing.JLabel DialogBox;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Garden;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
