/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pixelshop;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.prefs.Preferences;

/**
 *
 * @author redmibook
 */
public class Setting extends javax.swing.JFrame {

    /**
     * Creates new form DashKepala
     */
    private Preferences prefs = Preferences.userRoot().node("pixelshop");
    private int currentVolume = 45; // default 45%

    private void changeVolumeBy(int delta) {
        currentVolume += delta;
        if (currentVolume > 100) {
            currentVolume = 100;
        }
        if (currentVolume < 0) {
            currentVolume = 0;
        }

        // Update volume label (you have jText2 for volume display)
        jText2.setText(currentVolume + "%");

        // Update volume live (optional: you can choose to apply only on Save)
        AudioPlayer.getInstance().setVolume(currentVolume / 100f);
    }

    public Setting() {
        setTitle("Fixed Size Window");

        // Set fixed window size
        setSize(1440, 720); // Width = 800px, Height = 600px

        // Center the window on the screen
        setLocationRelativeTo(null);

        setResizable(false);

        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        initComponents();
        try {
            Font Text = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(40f);
            Font Button = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(30f);
            Font Heading = Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/DeterminationSansWebRegular-369X.ttf")).deriveFont(60f);
            Cancel.setFont(Button);
            Pass.setFont(Text);
            Save.setFont(Button);
            Discard.setFont(Button);
            volumeDown.setFont(Text);
            volumeUp.setFont(Text);
            Title.setFont(Heading);
            jText1.setFont(Text);
            jText2.setFont(Text);
            currentVolume = prefs.getInt("musicVolume", 45);
            jText2.setText(currentVolume + "%");
            AudioPlayer.getInstance().setVolume(currentVolume / 100f);

        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
        }

    }

// ...
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        volumeUp = new javax.swing.JButton();
        volumeDown = new javax.swing.JButton();
        Pass = new javax.swing.JButton();
        jText2 = new javax.swing.JLabel();
        jText1 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Discard = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        DialogBox = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 720));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volumeUp.setBackground(new java.awt.Color(255, 255, 255,0));
        volumeUp.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        volumeUp.setForeground(new java.awt.Color(255, 255, 255));
        volumeUp.setText("+");
        volumeUp.setBorder(null);
        volumeUp.setBorderPainted(false);
        volumeUp.setFocusPainted(false);
        volumeUp.setFocusable(false);
        volumeUp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        volumeUp.setOpaque(false);
        volumeUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volumeUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volumeUpMouseExited(evt);
            }
        });
        volumeUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeUpActionPerformed(evt);
            }
        });
        jPanel1.add(volumeUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 30, 30));

        volumeDown.setBackground(new java.awt.Color(255, 255, 255,0));
        volumeDown.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        volumeDown.setForeground(new java.awt.Color(255, 255, 255));
        volumeDown.setText("-");
        volumeDown.setBorder(null);
        volumeDown.setBorderPainted(false);
        volumeDown.setFocusPainted(false);
        volumeDown.setFocusable(false);
        volumeDown.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        volumeDown.setOpaque(false);
        volumeDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volumeDownMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volumeDownMouseExited(evt);
            }
        });
        volumeDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeDownActionPerformed(evt);
            }
        });
        jPanel1.add(volumeDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 30, 30));

        Pass.setBackground(new java.awt.Color(255, 255, 255,0));
        Pass.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Pass.setForeground(new java.awt.Color(255, 255, 255));
        Pass.setText("Edit Password");
        Pass.setBorder(null);
        Pass.setBorderPainted(false);
        Pass.setFocusPainted(false);
        Pass.setFocusable(false);
        Pass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Pass.setOpaque(false);
        Pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PassMouseExited(evt);
            }
        });
        Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassActionPerformed(evt);
            }
        });
        jPanel1.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 260, 50));

        jText2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jText2.setForeground(new java.awt.Color(255, 255, 255));
        jText2.setText("100%");
        jPanel1.add(jText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 100, 130));

        jText1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jText1.setForeground(new java.awt.Color(255, 255, 255));
        jText1.setText("Master Volume");
        jPanel1.add(jText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 270, 130));

        Title.setFont(new java.awt.Font("Lucida Calligraphy", 1, 60)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("CONFIG");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 250, 130));

        Discard.setBackground(new java.awt.Color(255, 255, 255,0));
        Discard.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Discard.setForeground(new java.awt.Color(255, 255, 255));
        Discard.setText("* DEFAULT");
        Discard.setBorder(null);
        Discard.setBorderPainted(false);
        Discard.setFocusPainted(false);
        Discard.setFocusable(false);
        Discard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Discard.setOpaque(false);
        Discard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DiscardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DiscardMouseExited(evt);
            }
        });
        Discard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscardActionPerformed(evt);
            }
        });
        jPanel1.add(Discard, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 590, 150, 30));

        Save.setBackground(new java.awt.Color(255, 255, 255,0));
        Save.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("* APPLY");
        Save.setBorder(null);
        Save.setBorderPainted(false);
        Save.setFocusPainted(false);
        Save.setFocusable(false);
        Save.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Save.setOpaque(false);
        Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SaveMouseExited(evt);
            }
        });
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 590, 130, 30));

        Cancel.setBackground(new java.awt.Color(255, 255, 255,0));
        Cancel.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        Cancel.setForeground(new java.awt.Color(255, 255, 255));
        Cancel.setText("* BACK");
        Cancel.setBorder(null);
        Cancel.setBorderPainted(false);
        Cancel.setFocusPainted(false);
        Cancel.setFocusable(false);
        Cancel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cancel.setOpaque(false);
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelMouseExited(evt);
            }
        });
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 590, 110, 30));

        DialogBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/cartbox.png"))); // NOI18N
        DialogBox.setText("jLabel3");
        jPanel1.add(DialogBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pixelshop/download.gif"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -490, 2110, 1620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseEntered
        // TODO add your handling code here:
        Cancel.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_CancelMouseEntered

    private void CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseExited
        // TODO add your handling code here:
        Cancel.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_CancelMouseExited

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void SaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseEntered
        // TODO add your handling code here:
        Save.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_SaveMouseEntered

    private void SaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseExited
        // TODO add your handling code here:
        Save.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_SaveMouseExited

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        prefs.putInt("musicVolume", currentVolume);
        JOptionPane.showMessageDialog(this, "Settings saved.");
    }//GEN-LAST:event_SaveActionPerformed

    private void DiscardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiscardMouseEntered
        // TODO add your handling code here:
        Discard.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_DiscardMouseEntered

    private void DiscardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiscardMouseExited
        // TODO add your handling code here:
        Discard.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_DiscardMouseExited

    private void DiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscardActionPerformed
        currentVolume = 45;
        jText2.setText(currentVolume + "%");
        AudioPlayer.getInstance().setVolume(currentVolume / 100f);
    }//GEN-LAST:event_DiscardActionPerformed

    private void volumeDownMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volumeDownMouseEntered
        // TODO add your handling code here:
        volumeDown.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_volumeDownMouseEntered

    private void volumeDownMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volumeDownMouseExited
        // TODO add your handling code here:
        volumeDown.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_volumeDownMouseExited

    private void volumeDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeDownActionPerformed

        currentVolume = Math.max(0, currentVolume - 5);
        jText2.setText(currentVolume + "%");
        AudioPlayer.getInstance().setVolume(currentVolume / 100f);
    }//GEN-LAST:event_volumeDownActionPerformed

    private void volumeUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volumeUpMouseEntered
        // TODO add your handling code here:
        volumeUp.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_volumeUpMouseEntered

    private void volumeUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volumeUpMouseExited
        // TODO add your handling code here:
        volumeUp.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_volumeUpMouseExited

    private void volumeUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeUpActionPerformed
        // TODO add your handling code here:
        currentVolume = Math.min(100, currentVolume + 5);
        jText2.setText(currentVolume + "%");
        AudioPlayer.getInstance().setVolume(currentVolume / 100f);
    }//GEN-LAST:event_volumeUpActionPerformed

    private void PassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassMouseEntered
        Pass.setForeground(new java.awt.Color(255, 239, 0));
    }//GEN-LAST:event_PassMouseEntered

    private void PassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassMouseExited
        Pass.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_PassMouseExited

    private void PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassActionPerformed
       int userId = User.currentUserId; // ID user yang sedang login
Connection conn = null;
PreparedStatement ps = null;

try {
    conn = koneksi.getKoneksi();

    // Input password baru
    String newPassword = JOptionPane.showInputDialog(this, "Enter new password:");
    if (newPassword == null || newPassword.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Password change canceled.");
        return;
    }

    // Konfirmasi password baru
    String confirmPassword = JOptionPane.showInputDialog(this, "Confirm new password:");
    if (!newPassword.equals(confirmPassword)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match!");
        return;
    }

    // Update password di database
    String sql = "UPDATE user SET password = ? WHERE id_user = ?";
    ps = conn.prepareStatement(sql);
    ps.setString(1, newPassword.trim());
    ps.setInt(2, userId);

    int rows = ps.executeUpdate();
    if (rows > 0) {
        JOptionPane.showMessageDialog(this, "Password successfully changed.");
    } else {
        JOptionPane.showMessageDialog(this, "User not found?");
    }

} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error changing password: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
} finally {
    try { if (ps != null) ps.close(); } catch (SQLException ignored) {}
    // koneksi tidak ditutup agar tetap bisa dipakai
}

    }//GEN-LAST:event_PassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel DialogBox;
    private javax.swing.JButton Discard;
    private javax.swing.JButton Pass;
    private javax.swing.JButton Save;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jText1;
    private javax.swing.JLabel jText2;
    private javax.swing.JButton volumeDown;
    private javax.swing.JButton volumeUp;
    // End of variables declaration//GEN-END:variables
}
